name: GitHub Actions Setup
on: [push]
jobs:
  Build-Docker-Image:
    runs-on: ubuntu-latest
    name: Build The Docker Image
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: docker build . --file Dockerfile --tag workoutdataapp:$(date)
      - run: echo "This job's status is ${{ job.status }}."
      - run: docker run workoutdataapp:$(date)
  # Infra-setup:
  # Run-test:
